project:
  type: website

website:
  title: "IS415-GAA"
  navbar:
    left:
      - text: "Hands-on exercise"
        menu: 
          - wk2.qmd
      - text: "In-class exercise"
        menu: 
          - text: "In class 1"
            href: "in-class-exercise/wk2/wk2/wk2.qmd"
    right: 
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

