project:
  type: website

website:
  title: "IS415-GAA"
  navbar:
    left:
      - text: "Hands-on exercise"
        menu: 
          - text: "Hands-on exercise 2"
            
          - text: "Hands-on exercise 3"
            href: "hands-on-exercise/wk3/HOE_Wk3.qmd"
          - text: "Hands-on exercise 4 and 5"
            href: "hands-on-exercise/wk4/HOE_wk4.qmd"
          - text: "Hands-on-exercise wk6"
            href: "hands-on-exercise/wk6/hoe_wk6.qmd"
          - text: "Hands-on exercise week 7"
            href: "hands-on-exercise/wk7/hoe_wk7.qmd"
          
      - text: "In-class exercise"
        menu: 
          - text: "In-class exercise 2"
            href: "in-class-exercise/wk2/wk2/wk2.qmd"
          - text: "In-class exercise 3"
            href: "in-class-exercise/wk3/ice_w3.qmd"
          - text: "In-class exercise 4"
            href: "hands-on-exercise/wk4/HOE_wk4.qmd"
          - text: "In-class exercise 5"
            href: "in-class-exercise/wk5/ICE_wk5.qmd"
          - text: "In-class exercise 6"
            href: "in-class-exercise/wk6/ice_wk6.qmd"
          - text: "In-class exercise 6"
            href: "in-class-exercise/wk7/ice_wk7.qmd"
      - text: "Take home exercise"
        menu: 
          - text: "Take home exercise 1"
            href: "Takehome_exercise/TakeHome1/TakeHome_ex1.qmd"
          - text: "Take-home exercise 2"
            href: "Takehome_exercise/TakeHome2/Takehome_ex2.qmd"
    right: 
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

